### ISSUE TITLE
`sync_utils.pulsealign()` bug using `Tuple[np.ndarray, np.ndarray]`

### ISSUE THREAD

**Issue by shawnrhoads** [seqasim/LFPAnalysis#43]
Importing `sync_utils` with Python 3.10.8 throws this error:

```
[autoreload of LFPAnalysis.sync_utils failed: Traceback (most recent call last):
  File "/sc/arion/work/rhoads01/envs/lfp_env/lib/python3.10/site-packages/IPython/extensions/autoreload.py", line 261, in check
    superreload(m, reload, self.old_objects)
  File "/sc/arion/work/rhoads01/envs/lfp_env/lib/python3.10/site-packages/IPython/extensions/autoreload.py", line 459, in superreload
    module = reload(module)
  File "/sc/arion/work/rhoads01/envs/lfp_env/lib/python3.10/importlib/__init__.py", line 169, in reload
    _bootstrap._exec(spec, module)
  File "<frozen importlib._bootstrap>", line 619, in _exec
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/sc/arion/projects/guLab/Shawn/tools/LFPAnalysis/LFPAnalysis/sync_utils.py", line 23, in <module>
    def pulsealign(beh_ms: np.ndarray, pulses: np.ndarray, windSize: int = 30) -> Tuple[np.ndarray, np.ndarray]:
NameError: name 'Tuple' is not defined
]
```

I believe this is due to the capital `T`:
```
def pulsealign(beh_ms: np.ndarray, pulses: np.ndarray, windSize: int = 30) -> Tuple[np.ndarray, np.ndarray]:
```

Changing to lowercase removes the error.
```
def pulsealign(beh_ms: np.ndarray, pulses: np.ndarray, windSize: int = 30) -> tuple[np.ndarray, np.ndarray]:
```

**Comment by seqasim** [comment]
Fixed in commit [f7b2735](https://github.com/seqasim/LFPAnalysis/commit/f7b27351f871889e4943aa221ef5552317a6e992)
